FROM ubuntu:latest

ADD requirements.txt bdd_datascientest_projet3.db api.py ./

RUN apt-get update -y && \
    apt-get install -y python3 && \
    apt-get install -y python3-pip && \
    apt-get install libssl-dev libffi-dev  

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir requests && \
    pip install -r requirements.txt

EXPOSE 5010

CMD python3 api.py
